#!/bin/sh -e

case "$1" in
upgrade|remove)
    # Remove symbolic links
    rm -f /usr/bin/ldns-keygen
    rm -f /usr/bin/ldns-key2ds
    rm -f /usr/bin/ldns-nsec3-hash
    rm -f /usr/bin/ldns-notify
    rm -f /usr/bin/ldns-signzone
    rm -f /usr/bin/ldns-update
    ;;
esac
